service: starwars-api
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-2
  memorySize: 128
  apiGateway:
    binaryMediaTypes:
      - "*/*"
functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-dotenv-plugin
