service: starwars-api
provider:
  name: aws
  profile: eduardo-mio
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128
  apiGateway:
    binaryMediaTypes:
      - "*/*"
functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-dotenv-plugin
